### ISSUE TITLE
BadPaddingException

### ISSUE THREAD

**Issue by ArjunDandagi** [uweguenther/maven-password-decryptor#2]
```
Exception in thread "main" org.sonatype.plexus.components.cipher.PlexusCipherException: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at org.sonatype.plexus.components.cipher.PBECipher.decrypt64(PBECipher.java:193)
	at org.sonatype.plexus.components.cipher.DefaultPlexusCipher.decrypt(DefaultPlexusCipher.java:74)
	at org.sonatype.plexus.components.cipher.DefaultPlexusCipher.decryptDecorated(DefaultPlexusCipher.java:91)
	at de.cscc.maven.MavenPasswordDecryptor.main(MavenPasswordDecryptor.java:19)
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2168)
	at org.sonatype.plexus.components.cipher.PBECipher.decrypt64(PBECipher.java:185)
	... 3 more
```

I am trying to pass both master and password as your suggestion 

java -jar maven-password-decryptor.jar <password_within_curly_braces> <master_pwd_within_curly_braces>

am i missing something here? 

> java -version 
1.8.0_252

**Comment by uweguenther** [comment]
What exactly are you typing in Arjun? 
Why are you using curly braces?

Thats what the usage comment says:

Usage: java -jar maven-password-decryptor.jar <encrypted-password>
Usage: java -jar maven-password-decryptor.jar <encrypted-password> <master-password>

Uwe

**Comment by ArjunDandagi** [comment]
@uweguenther   no i mean i am only typing the characters inside the curly braces. not including them . 

for some reason i am unable to decrypt. tried with and without the master password :)
